### ISSUE TITLE
Embedding h5p content elsewhere

### ISSUE THREAD

**Issue by axza** [studer-raimann/H5P#11]
It would be great if we could embed H5P self-tests (created in ILIAS) in the middle of a learning module or elsewhere.
#enhancement

**Comment by theodortruffer** [comment]
Hey @axza 
Check out the H5PPageComponent-Plugin (https://github.com/studer-raimann/H5PPageComponent). It allows you to create H5P-Content in any place where the ILIAS page editor can be used. 
Is that what you were looking for?

**Comment by axza** [comment]
this helps for h5p-content inside ILIAS.
Thank you!

on the other hand, we want to embed already existing h5p material in our open learning env. ([learn.opengeoedu.de](https://learn.opengeoedu.de)).
Content created at h5p.org has an 'embed' button - how to enable this for "ilias hosted" content?

**Comment by theodortruffer** [comment]
I'm afraid that's not possible at the moment. 

Content from h5p.org is public and accessible for everyone, so it's no problem to embed it via iframe on another website. Content created in ILIAS on the other hand is privately stored in ILIAS and needs authentication to be accessed. Therefore it's not enough to just enable the button, we would have to implement the functionality (something like a checkbox "set content public/allow embedding").  

Please contact us if you are interested in funding such a feature. Unfortunately we won't be able to implement such a feature without further funding.

**Comment by srgitlab** [comment]
Moved to Jira
