### ISSUE TITLE
No file upload with iframe embedder

### ISSUE THREAD

**Issue by fsesterh** [studer-raimann/H5P#12]
H5P allows to use the content type "iframe embedder" in order to embed individual HTML5 content via iframe. The use case for the content-type suggests two options to do so: 1) to supply the HTML5 content by URL or 2) to upload the HTML5 content to the "content" folder. In ILIAS this folder is located here:
[ILIASROOT]/data/[CLIENTID]/h5p/content]

However, the H5P Plugin does not support a file upload to the given location.

Will this be supported in the future?

**Comment by srgitlab** [comment]
implemented in v2.1.0 and v2.1.1
