### ISSUE TITLE
Upgrade available filter contains already upgraded libraries

### ISSUE THREAD

**Issue by fsesterh** [studer-raimann/H5P#13]
The H5P hub GUI lets you filter for libraries for which an upgrade is available. This filter is pretty useless though, because the plugin does not store / save if a version of a library has been updated already. The filtered view (filtered for "upgrade available = yes") will always list ALL libraries which version number is older than the latest available, even if a later version of the library as already been installed. The root cause of this is that sometimes an older version cannot be deleted by upgrading it, due to content using the old library.

What it should do is to only list libraries that are not the latest version AND for which no later version has already been installed, proving admins a list the can use to upgrade all libraries with ease and not miss anything.

**Comment by srgitlab** [comment]
Moved to Jira
