### ISSUE TITLE
Plugin configuration error - ILIAS 5.2.20

### ISSUE THREAD

**Issue by dymitar** [studer-raimann/H5P#14]
The plugin configuration throws error if you try to go to Settings tab of the configuration.
ilErrorHandling::{closure}:50 4 syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /var/www/xxx/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/srag/activerecordconfig/src/ActiveRecordConfigFormGUI.php:54

Everything else is working, the HUB configuration, the repository object itself.

Tested with ILIAS 5.3, the same error.

**Comment by srgitlab** [comment]
Fixed in v2.1.1, a bug because PHP 7 synthax under PHP 5
