### ISSUE TITLE
Problem with missing library translation

### ISSUE THREAD

**Issue by dymitar** [studer-raimann/H5P#15]
If your ILIAS language is not translated in H5P libraries, the library is not working properly.
For example Course Presentation library doesn't show the buttons and fields and shows only "Missing Translation..."
To fix this we need a fallback to english. Here is the solution for the problem:
https://github.com/h5p/h5p-editor-php-library/commit/372449382a2c9a11fd1b12db6d5e88089ff1e9b8

Adding this
`		// If translation was not found, and this is not the English one, try to load
        // the English translation
        if ($translation === NULL && $languageCode !== 'en') {
          $translation = $this->getLibraryLanguage($library['machineName'], $library['majorVersion'], $library['minorVersion'], 'en');
        }
`
 to H5P/vendor/h5p/h5p-editor/h5peditor.class.php (after line 436) fixes the problem.

**Comment by srgitlab** [comment]
Fix in v2.1.1, updated to latest h5p-editor 1.8.2
