### ISSUE TITLE
H5P object error in Settings tab ILIAS 5.2.20 (PHP 5.6)

### ISSUE THREAD

**Issue by dymitar** [studer-raimann/H5P#16]
There is an error in settings tab of H5P repository object.
ilErrorHandling::{closure}:50 4 syntax error, unexpected ':', expecting ';' or '{' in /...../Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/srag/custominputguis/src/PropertyFormGUI/ObjectPropertyFormGUI.php:133
Replacing 
`protected final function strToCamelCase($string): string {`
with 
`protected final function strToCamelCase($string) {`

Fixes the issue
I don't know if the return type is essential when the system is running with  PHP 7, but I think the function will work fine without it.

**Comment by srgitlab** [comment]
Fixed in v2.1.2
