### ISSUE TITLE
Unable to refresh HUB

### ISSUE THREAD

**Issue by sslotosch** [studer-raimann/H5P#4]
Just installed the plugin on an ILIAS 5.3.5. 
Installation worked fine but I don't get to see any libraries on the HUB-page and whenever I klick on "Resresh HUB" (sic!) I get the message
"The H5P Hub has been disabled until this problem can be resolved. You may still upload libraries through the "H5P Libraries" page."

**Comment by theodortruffer** [comment]
We couldn't reproduce this bug. The error message is not coming from the code of our plugin but probably from the H5P library. We're guessing this is an issue of the connection from your server to the H5P HUB. Maybe there is some firewall blocking the connection.

Can you try to curl/ping h5p.org from the server where your ILIAS is installed?

**Comment by sslotosch** [comment]
Pinging h5p.org works fine. The funny thing is that the Plugin works on a second ILIAS with 5.2.16 installed, while on a third ILIAS, also with 5.2.16 installed it doesn't.

**Comment by sslotosch** [comment]
Btw... Do you know which protocol is used and which port would have to be opened? The original server where the plugin will be used on is protected by a firewall.

**Comment by theodortruffer** [comment]
The plugins sends a HTTP (or HTTPS) GET request to http(s)://api.h5p.org/v1/sites, so I'm guessing the ports 80, or 443 respectively, should be enough. You can also try whitelisting the IP of h5p.org (139.59.212.216).

If you can send a curl request from your server to http(s)://api.h5p.org/v1/sites then it should should (actually..) be possible to load the hub.

Let me know if you have any news on this.

**Comment by theodortruffer** [comment]
I just talked to our sysadmin - it seems that pinging uses another protocol. So to test the firewall, you'll have to use curl, for example. Just try something like "curl https://api.h5p.org/v1/sites".

**Comment by sslotosch** [comment]
curl -v https://api.h5p.org/v1/sites works on all three servers.

**Comment by theodortruffer** [comment]
Then I'm afraid I'm out of ideas at the moment.. But since the issue lies inside the H5P library, I suggest you ask the H5P developers for help. 
Sorry about that - I will get back to you if we find something. If you should be able to fix it, please let us know, too.

**Comment by srgitlab** [comment]
Moved to Jira
