### ISSUE TITLE
Unable to remove "summary task" in Interactive Video

### ISSUE THREAD

**Issue by sslotosch** [studer-raimann/H5P#7]
Within teh Interactive Video it is possible to set up a summary task that shows up at the end of the video (or wherever it is placed). When Using H5P within moodle or WordPress it is also possible to delete the summary task. Within the ILIAs-Plugin this isn't possible. I always get asked to fill in the summary task.

**Comment by theodortruffer** [comment]
I created a ticket in our internal task system. Unfortunately, this could take a while, since our responsible developer is currently on holiday and we are short on resources in general. I will try to get back to you as soon as possible.

**Comment by MichelleKubier** [comment]
Hello, will this be fixed anytime soon?

**Comment by theodortruffer** [comment]
In fact, we just released version 2.0.0 of the plugin (a few minutes ago :)). The issue should be fixed in this version.
