### ISSUE TITLE
Object-Icon way too big in List of materials for Sessions

### ISSUE THREAD

**Issue by MichelleKubier** [studer-raimann/H5P#8]
In the Tab "Materials" of Sessions the SVG is not sized as it should be, see attached screenshot. Is this something you can fix?

![h5p_sessionmaterials](https://user-images.githubusercontent.com/32267686/43005232-c1017652-8c21-11e8-9cc9-680b57cb5bdf.png)

**Comment by theodortruffer** [comment]
This bug was fixed just now. Please check out the latest version and delete your browser's cache. I'll close this issue - if you still experience this, just comment/reopen it.
